### ISSUE TITLE
Interceptors not applying headers

### ISSUE THREAD

**Issue by robertmain** [balderdashy/angularSails#26]
I'm having a problem applying the following interceptor to sailsSocket.

Given the following in my config block:

```
$sailsSocketProvider.interceptors.push(function($q){
    return {
        request: function(config){
            $sailsSocketProvider.defaults.headers.foo = "bar";
            return config;
        }
    }
});
```

The interceptor is firing, I can see from chrome inspector that the interceptors are not being applied to the outgoing requests.

**Comment by mattblang** [comment]
This would be amazing!  I'm trying to tie in [angular-jwt's Interceptor](https://github.com/auth0/angular-jwt#jwtinterceptor) for authentication.
