### ISSUE TITLE
change in bower.json to report support for angular 1.4

### ISSUE THREAD

**Issue by cwoloszynski** [balderdashy/angularSails#62]
The current bower.json file says that the code needs angular 1.2.  I am trying to use 1.3 and have to have a bower install work without errors/warnings.  Since you have fixed this to work with 1.4, can I ask that the bower file be updated to reflect this relaxed dependency?

**Comment by robwormald** [comment]
sure. i've wanted to make 1.3 the baseline anyway, since I can use the new $q syntax. i'll do it in the next couple of days.

**Comment by cwoloszynski** [comment]
Much appreciated.

**Comment by robwormald** [comment]
doneski
