### ISSUE TITLE
Missing a ) in dist/ngsails.io.js

### ISSUE THREAD

**Issue by remimanue** [balderdashy/angularSails#63]
Hi,
since you change 'module.prefix' in v0.11.4 Mozilla console report an error ''Missing a )" in dist/ngsails.io.js  when injected. No problem with src directory, so i think it's a build problem, not a code problem. The content of 'module.suffix' should be something like:
<pre>}));</pre>

**Comment by charlesDADI** [comment]
please could you precise the line

**Comment by robwormald** [comment]
this should have only been on master, but its reverted anyway - please use the release versions as master is often not production ready.
