### ISSUE TITLE
$sailsSocket.get is not a function

### ISSUE THREAD

**Issue by idrakimuhamad** [balderdashy/angularSails#66]
I'm getting this error for anything related to the $sailsSocket eg `.on, .subscribe`. I've included in my main module `angularSails.io` and `$sailsSocket` in my controller.

I'm using the latest version 0.12.1. Do I need to include `sails.io` too?

**Comment by robwormald** [comment]
yes, for the moment you need to include sails.io

**Comment by idrakimuhamad** [comment]
Hey @robwormald  sorry to add up. Apparently, I'm getting this because I'm actually wish to listen from my other app at 8080. So I'm looking for ways to declare this default URL, and saw #30 and tried that, it works. Awesome.

But on production, when my code was compiled and serve up on S3, how do I get this URL works again? At the moment, we bundle all vendor stuff into one file so, I don't see a way to put the `io.sails.url = "http://url"` anywhere.

Can you guys give some suggestion on this?

**Comment by robwormald** [comment]
Ugh, I really need to pull sails.io and replace it, shouldn't be this difficult. Apologies. 

Best thing to do meanwhile would be to create a file (sailsconfig.js or w/e) and concat that in.

**Comment by idrakimuhamad** [comment]
alright. no worries.
